"""empty message

Revision ID: d4a1395e6dbc
Revises: 58d997b73487
Create Date: 2019-12-19 23:23:22.494227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a1395e6dbc'
down_revision = '58d997b73487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('released', sa.String(length=255), nullable=True),
    sa.Column('background_image', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('achiev_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.add_column('user_games', sa.Column('user_rating', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'user_games', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_games', type_='foreignkey')
    op.drop_column('user_games', 'user_rating')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
